name: Ping Render Service

on:
  schedule:
    # Run every 10 minutes instead of 14 (more reliable)
    - cron: '*/10 * * * *'
    # Backup: also run every 15 minutes offset by 5
    - cron: '5,20,35,50 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service URL
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.RENDER_SERVICE_URL }})
          if [ $response -eq 200 ]; then
            echo "✅ Successfully pinged Render service at $(date -u) - HTTP $response"
          else
            echo "❌ Failed to ping Render service at $(date -u) - HTTP $response"
            exit 1
          fi
